### ISSUE TITLE
AAD-Pod-Identity exception

### ISSUE THREAD

**Issue by simongottschlag** [XenitAB/terraform-modules#17]
https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/mic-exception.yaml

If the cluster has aad-pod-identity enabled, Node Managed Identity (NMI) pods modify the nodes' iptables to intercept calls to the Azure Instance Metadata endpoint. This configuration means any request made to the Metadata endpoint is intercepted by NMI even if the pod doesn't use aad-pod-identity. AzurePodIdentityException CRD can be configured to inform aad-pod-identity that any requests to the Metadata endpoint originating from a pod that matches labels defined in CRD should be proxied without any processing in NMI. The system pods with kubernetes.azure.com/managedby: aks label in kube-system namespace should be excluded in aad-pod-identity by configuring the AzurePodIdentityException CRD. For more information, see Disable aad-pod-identity for a specific pod or application. To configure an exception, install the mic-exception YAML.

**Comment by simongottschlag** [comment]
The exception for mic is created by default in the namespace the helm chart is installed:
```YAML
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: mic-exception
  namespace: default
spec:
  podLabels:
    app: mic
    component: mic
```

From cluster:
```shell
kubectl -n aad-pod-identity describe AzurePodIdentityException
Name:         mic
Namespace:    aad-pod-identity
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: aad-pod-identity
              meta.helm.sh/release-namespace: aad-pod-identity
API Version:  aadpodidentity.k8s.io/v1
Kind:         AzurePodIdentityException
Metadata:
[...]
Spec:
  Metadata:
    Creation Timestamp:  <nil>
  Pod Labels:
    App:                          mic
    app.kubernetes.io/component:  mic
    Component:                    mic
Status:
  Metadata:
    Creation Timestamp:  <nil>
  Status:
Events:                  <none>
```

**Comment by simongottschlag** [comment]
The exception for kube-system seems only to be needed when using addons from AKS that need their own MSI:
```YAML
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: aks-addon-exception
  namespace: kube-system
spec:
  podLabels:
    kubernetes.azure.com/managedby: aks
```

Skipping this for now.
