### ISSUE TITLE
Network policies

### ISSUE THREAD

**Issue by phillebaba** [XenitAB/terraform-modules#215]
All platform namespaces should configure network policies if applicable. Considerations should be made for access by the ingress controller and prometheus monitoring.

**Comment by phillebaba** [comment]
Suggested policy to apply in all tenant namespaces.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: untitled-policy
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
```
