### ISSUE TITLE
Export AKS cluster metrics

### ISSUE THREAD

**Issue by phillebaba** [XenitAB/terraform-modules#286]
AKS through Azure monitor exposes metris related to the cluster autoscaler which are otherwise not exported through the cluster metrics.
https://docs.microsoft.com/en-us/azure/aks/view-metrics

We should find a way to export these metrics as metrics like `cluster_autoscaler_cluster_safe_to_autoscale` can give better insight into the autoscaler.

**Comment by phillebaba** [comment]
Should be easily solved by using a metrics exporter.
https://github.com/RobustPerception/azure_metrics_exporter

**Comment by NissesSenap** [comment]
I have tested RobustPerception/azure_metrics_exporter with the following config:

```yaml
resource_groups:
  - resource_group: "rg-prod-we-aks"
    resource_types:
      - "Microsoft.ContainerService/managedClusters"
    metrics:
      - name: "cluster_autoscaler_cluster_safe_to_autoscale"
      - name: "cluster_autoscaler_scale_down_in_cooldown"
      - name: "cluster_autoscaler_unneeded_nodes_count"
      - name: "cluster_autoscaler_unschedulable_pods_count"
```

And we can see metrics that looks good. The problem is that it's not a super active project.

We will look at:
https://github.com/webdevops/azure-metrics-exporter
and see how that works.
