### ISSUE TITLE
Add documentation for working deployments with opa-gatekeeper

### ISSUE THREAD

**Issue by simongottschlag** [XenitAB/terraform-modules#31]
Example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: podinfo
          image: "acrdevweaks.azurecr.io/podinfo:5.0.3"
          imagePullPolicy: "IfNotPresent"
          command:
            - ./podinfo
            - --port=8080
            - --level=info
          env:
          - name: PODINFO_UI_MESSAGE
            value: "WELCOME TO PODINFO!"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            exec:
              command:
              - podcli
              - check
              - http
              - localhost:8080/readyz
            initialDelaySeconds: 1
            timeoutSeconds: 5
          volumeMounts:
          - name: data
            mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - NET_RAW
      volumes:
      - name: data
        emptyDir: {}
```
