### ISSUE TITLE
 Reconciliation failed with fluxcd-v2-azdo

### ISSUE THREAD

**Issue by jouros** [XenitAB/terraform-modules#392]
$ flux get kustomizations
NAME            READY   MESSAGE                                                                                                                                                                                                                                                                                                                                                                                                          REVISION                                        SUSPENDED
flux-system     False   failed to download artifact, error: GET http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/235d23973118a331c1042a44e012b23f911890ed.tar.gz giving up after 10 attempt(s): Get "http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/235d23973118a331c1042a44e012b23f911890ed.tar.gz": dial tcp 172.19.65.48:80: i/o timeout  main/235d23973118a331c1042a44e012b23f911890ed   False
tenants         Unknown reconciliation in progress
 
so this: clusters/dev/tenants.yaml does not get deployed?

**Comment by jouros** [comment]
kubectl logs -f kustomize-controller-7497fb6b78-zt7hn -n flux-system

{"level":"error","ts":"2021-09-02T11:00:01.583Z","logger":"controller.kustomization","msg":"Reconciliation failed after 8m35.028300927s, next try in 5m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"tenants","namespace":"flux-system","revision":"main/235d23973118a331c1042a44e012b23f911890ed","error":"failed to download artifact, error: GET http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/235d23973118a331c1042a44e012b23f911890ed.tar.gz giving up after 10 attempt(s): Get \"http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/235d23973118a331c1042a44e012b23f911890ed.tar.gz\": dial tcp 172.19.65.48:80: i/o timeout"}

I did not deploy network policies: 
```yaml
$ cat azdo-proxy-values.yaml.tpl
#priorityClassName: "platform-medium"
networkPolicy:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi
config: |
  {
    "organizations": [
      {
        "name": "${azure_devops_org}",
        "pat": "${azure_devops_pat}",
        "repositories": [
          %{ for tenant in tenants ~}
          {
            "project": "${tenant.project}",
            "name": "${tenant.repo}",
            "namespaces": ["${tenant.namespace}"],
            "secretNameOverride": "flux"
          },
          %{ endfor }
          {
            "project": "${azure_devops_proj}",
            "name": "${cluster_repo}",
            "namespaces": ["flux-system"],
            "secretNameOverride": "flux-system"
          }
        ]
      }
    ]
  }
```
