### ISSUE TITLE
kustomization path not found: stat /tmp/team3086200924/tenants/puretest: no such file or directory

### ISSUE THREAD

**Issue by jouros** [XenitAB/terraform-modules#402]
I did use newer values: terraform 1.0.6 and fluxcd/flux 0.3.1. After deployment I got this error: kustomization path not found: stat /tmp/team...

$ kubectl get kustomizations -n team3
NAME    READY   STATUS                                                                                               AGE
team3   False   kustomization path not found: stat /tmp/team3897174358/tenants/puretest: no such file or directory   2d1h

Same error for both used namespaces team3 and team4.

I had same value for environent and cluster_id 'puretest' and tenants set to 'team3' and 'team4'. 

$ kubectl get kustomizations -n team4 -o yaml

```yaml
apiVersion: v1
items:
- apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
  kind: Kustomization
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"kustomize.toolkit.fluxcd.io/v1beta1","kind":"Kustomization","metadata":{"annotations":{"kustomize.toolkit.fluxcd.io/checksum":"0ae0700d1c4bd3f8a292731d9b61afa8d1c22f5a"},"labels":{"kustomize.toolkit.fluxcd.io/name":"tenants","kustomize.toolkit.fluxcd.io/namespace":"flux-system"},"name":"team4","namespace":"team4"},"spec":{"interval":"5m","path":"./tenant/puretest","prune":true,"serviceAccountName":"flux","sourceRef":{"kind":"GitRepository","name":"team4"},"validation":"client"}}
      kustomize.toolkit.fluxcd.io/checksum: 0ae0700d1c4bd3f8a292731d9b61afa8d1c22f5a
    creationTimestamp: "2021-09-15T11:23:41Z"
    finalizers:
    - finalizers.fluxcd.io
```

My infra Git repo does not have ./tenant/... It has only ./tenants/puretest/
 
]$ kubectl describe kustomization team4 -n team4

```txt
Events:
  Type    Reason  Age                  From                  Message
  ----    ------  ----                 ----                  -------
  Normal  error   1s (x590 over 2d1h)  kustomize-controller  (combined from similar events): kustomization path not found: stat /tmp/team4214867973/tenant/puretest: no such file or directory
```

I tested below config manually to change path from 'tenant' to 'tenants' but it did not change behavior:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: team3
  namespace: team3
spec:
  serviceAccountName: flux
  interval: 5m
  path: ./tenants/puretest
  sourceRef:
    kind: GitRepository
    name: team3
  prune: true
  validation: client
```

helm deployment is working as expetced.

**Comment by simongottschlag** [comment]
Hi @jouros!

Can you share some more details on how you are deploying and the resulting GitRepository for the team?

**Comment by jouros** [comment]
Some tfvars used in deployment:

```text
flux_cluster_repo                   = "infra1"
flux_environment                    = "puretest"
flux_cluster_id                     = "puretest"
flux_namespaces                     = [
                                      {
                                      name = "team3"
                                        flux = {
                                          enabled      = true
                                          create_crds  = true
                                          org          = "myorg"
                                          proj         = "infra"
                                          repo         = "team3"
                                        }
                                      },

                                      {
                                      name = "team4"
                                        flux = {
                                          enabled      = true
                                          create_crds  = true
                                          org          = "myorg"
                                          proj         = "infra"
                                          repo         = "team4"
                                        }
                                      }
                                      ]
dockerpull_tenants                   = ["team3", "team4"]
namespaces_tenants                   = ["team3", "team4"]
```

In Git:  
 ls -R clusters/puretest/  
clusters/puretest/:  
flux-system  tenants.yaml  

clusters/puretest/flux-system:  
gotk-components.yaml  gotk-sync.yaml  kustomization.yaml  

ls -R tenants/puretest  
tenants/puretest:  
team3-hr.yaml  team3.yaml  team4.yaml <= team3-hr = helm release test deployment and that is working as expected.   

In tenants/puretest/team3.yml (I changed that manually as I explained above):  

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: team3
  namespace: team3
spec:
  serviceAccountName: flux
  interval: 5m
  path: ./tenants/puretest
  sourceRef:
    kind: GitRepository
    name: team3
  prune: true
  validation: client
```

/clusters/puretest/tenants.yaml:  

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/puretest
  prune: true
  validation: client
```

Below is orig version as it was deployed by module and here it use phrase 'tenant' which does not exist in Git:  

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: team4
  namespace: team4
spec:
  serviceAccountName: flux
  interval: 5m
  path: ./tenant/puretest
  sourceRef:
    kind: GitRepository
    name: team4
  prune: true
  validation: client
```

I made new deployment 'puretest2' with repos 'team1' and 'team2' and it had same error as in above deployment:  

```text
$ flux get kustomizations -n team1
NAME    READY   MESSAGE                                                                                                 REVISION        SUSPENDED
team1   False   kustomization path not found: stat /tmp/team1467684528/tenant/puretest2: no such file or directory                      False
```

tenants/puretest2$ cat team1.yaml  

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: team1
  namespace: team1
spec:
  serviceAccountName: flux
  interval: 5m
  path: ./tenant/puretest2
  sourceRef:
    kind: GitRepository
    name: team1
  prune: true
  validation: client
```
